backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "منشورات كابوس حلفا"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "عنوان الخبر", name: "title", widget: "string" }
      - { label: "تاريخ النشر", name: "date", widget: "datetime" }
      - { label: "صورة الخبر", name: "image", widget: "image", required: false }
      - { label: "تفاصيل الخبر", name: "body", widget: "markdown" }
